### ISSUE TITLE
A question of calculating 95% confidence interval

### ISSUE THREAD

**Issue by czifan** [LinLu1912/CNN-RNN-paper#2]
Hello, thanks for sharing this interesting work! It is helpful for me.

I have a question that how to calculate the 95% confidence inverval in Table 4. 

Look forward for your reply. thank you very much!

**Comment by LinLu1912** [comment]
Hi,

The 95% CI for C-Index were attained using the function *concordance.index*
in the *R package 'survcomp'* (see the link below, please).

https://www.rdocumentation.org/packages/survcomp/versions/1.22.0/topics/concordance.index

Best regards,

Lin

**Comment by czifan** [comment]
Thanks!!!
